import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/layouts/nav-bar";
import Provider from "@/provider/Provider";
import IsMobileDevice from "@/components/IsMobileDevice";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Provider>
                    <>
                        <IsMobileDevice />
                        <NavBar />
                        <div className="px-4 md:max-w-[80%] mx-auto">{children}</div>
                    </>
                </Provider>
            </body>
        </html>
    );
}
